### PR TITLE
final-task

### PR DESCRIPTION
**Pull request by Tanushree-coder**
Issue: 331

#### Short description of what this resolves:

added figma link

#### Changes proposed in this pull request and/or Screenshots of changes:

image

### CODE REVIEW

**Comment by Manav1410** [comment]
can you provide some description of what you have made

**Comment by Tanushree-coder** [comment]
> can you provide some description of what you have made

used the symbol of code,i.e, **</>** to show the coding as major part of open source.

**Comment by Manav1410** [comment]
what does the eye represent?

**Comment by Tanushree-coder** [comment]
> what does the eye represent?

to keep an eye on the upcoming issues.

**Comment by Tanushree-coder** [comment]
@Manav1410 can you suggest some changes?

**Comment by Manav1410** [comment]
Yup, increase the spacing b/w eye and opening bracket. The design looks cluttered.

**Comment by Tanushree-coder** [comment]
> Yup, increase the spacing b/w eye and opening bracket. The design looks cluttered.

done.

**Pull request merged**
