### PR TITLE
Added doc link

### PR DESCRIPTION
**Pull request by jalanprakhar**
Issue: 1

#### Short description of what this resolves:

Added doc link

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Manav1410** [comment]
Too many fonts used. Inconsistent. Readability is very poor

**Comment by jalanprakhar** [comment]
@Manav1410 is rest everything fine? i will just even out the font

**Comment by Manav1410** [comment]
> @Manav1410 is rest everything fine? i will just even out the font

Yup, Rest is fine...

**Comment by jalanprakhar** [comment]
@Manav1410 you closed the issue can i submit it now?

**Pull request closed without merging**
