### PR TITLE
Added final task

### PR DESCRIPTION
**Pull request by shlesh**
Issue: 331

#### Short description of what this resolves:

shlesh

#### Changes proposed in this pull request and/or Screenshots of changes:

### CODE REVIEW

**Comment by Manav1410** [comment]
read the issue again. You have done logo design instead of minimal poster

**Comment by shlesh** [comment]
> 
> 
> read the issue again. You have done logo design instead of minimal poster

Oops sorry, I saw some examples that looked like logos and got confused in the rush, will fix it asap

**Comment by shlesh** [comment]
@Manav1410 sir can you please review this version🥺🥺

**Comment by Manav1410** [comment]
check out the inspirations given in the task description. You had to use icons and text together creatively. Here, all the elements are different😕

**Comment by shlesh** [comment]
@Manav1410 sir is this better now?🥺🥺🥺🥺
ive really been doing only this issue since then

**Comment by Manav1410** [comment]
Not looking good 😕

**Comment by shlesh** [comment]
> 
> 
> Not looking good 😕

badhiya hai

**Pull request closed without merging**
