### PR TITLE
The final task

### PR DESCRIPTION
**Pull request by shashwat-mittal**
Issue: 331

#### Short description of what this resolves:
Frame 1 (13)

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by Manav1410** [comment]
can you explain your design a bit

**Comment by shashwat-mittal** [comment]
> can you explain your design a bit
@Manav1410 please check it now

**Comment by Manav1410** [comment]
can you explain your design a bit, like what have represented using the elements that you have used

**Comment by shashwat-mittal** [comment]
> can you explain your design a bit, like what have represented using the elements that you have used

i tried to show open with the opening lid design, it can be assumed to open a world of open source contribution

**Pull request merged**
