### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by codesanta142**
Issue: 1

#### Short description of what this resolves:
Typography

#### Changes proposed in this pull request and/or Screenshots of changes:

-
image

-
-

### CODE REVIEW

**Comment by ShreyaShrotriya** [comment]
This submission closely resembles the submission made by another contributor. Please try again with an original approach.

**Comment by garvitchittora** [comment]
@codesanta142 If this happens again, then we will take action against this! 
We might ban you from Open Code as well as future geekhaven events.

Open Code is for learning.

**Comment by codesanta142** [comment]
@garvitchittora sir hierarchy will be same in the paragraph provided and the most common indexing was chosen in previous one , so it came to be similar. Although i have changed the font and indexing again to have a distiguished one.
Sorry.

**Comment by schandu-eng** [comment]
> @garvitchittora sir hierarchy will be same in the paragraph provided and the most common indexing was chosen in previous one , so it came to be similar. Although i have changed the font and indexing again to have a distiguished one.
> Sorry.
> 

Basically the hierarchy used by the previous submission was very much imperfect😂😂🤣 If you would have analysed or observed . And  if a thing is correct and it's done by many people then we can understand that it's something common.
But similarity with wrong/imperfect submission results strong suspension.

😐 Don't want to offend anyone but design is also a vast feel like other form of developments , people put hours of research and reading for doing even minute things , just taking design issues because they seem simple and dealing with them casually few points is meaningless , you will end up learning Nothing .

And if u wanna deep dive into design 👀👀 Geekhaven members are always very helpful and highly skillful (guruon ko pranaaam🙇‍♂️).

🫂✌️Peace

**Pull request closed without merging**
